events{
    #empty   
}

http{
    server {
        listen 80;
        root /usr/share/nginx/html;

        location /api/ {
            proxy_pass http://api:8000/;
        }

        location = /signup {
            try_files /auth/signup.html =404;
        }
        location = /login {
            try_files /auth/login.html =404;
        }
        location = /delete_user {
            try_files /auth/delete_user.html =404;
        }
        location = / {
            try_files /index.html =404;
        }

        location = /store/ {
            try_files /store/store.html =404;
        }

    }
}