# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nanolock.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'nanolock.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enanolock.proto\x12\x08nanolock\"2\n\x0b\x46\x61\x63\x65Request\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\"0\n\x0c\x46\x61\x63\x65Response\x12\x10\n\x08verified\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"5\n\x0e\x41\x64\x64UserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\"2\n\x0f\x41\x64\x64UserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t2\x87\x01\n\x08NanoLock\x12\x39\n\x06Verify\x12\x15.nanolock.FaceRequest\x1a\x16.nanolock.FaceResponse\"\x00\x12@\n\x07\x41\x64\x64User\x12\x18.nanolock.AddUserRequest\x1a\x19.nanolock.AddUserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nanolock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FACEREQUEST']._serialized_start=28
  _globals['_FACEREQUEST']._serialized_end=78
  _globals['_FACERESPONSE']._serialized_start=80
  _globals['_FACERESPONSE']._serialized_end=128
  _globals['_ADDUSERREQUEST']._serialized_start=130
  _globals['_ADDUSERREQUEST']._serialized_end=183
  _globals['_ADDUSERRESPONSE']._serialized_start=185
  _globals['_ADDUSERRESPONSE']._serialized_end=235
  _globals['_NANOLOCK']._serialized_start=238
  _globals['_NANOLOCK']._serialized_end=373
# @@protoc_insertion_point(module_scope)
